<#
.SYNOPSIS
  Patches DSROmniRoll Standalone v1.01 (d3d11.dll) so it works with the 2018-05-22 DarkSoulsRemastered.exe build.

.DESCRIPTION
  GENERATED by tools/port_omniroll.py --emit-ps1. Do not edit the patch table by hand.

  Checks that DarkSoulsRemastered.exe and d3d11.dll are the exact supported files (SHA-256), backs up the
  original DLL as d3d11.dll.orig, applies the port, and verifies the result.

.PARAMETER GameDir
  Folder that contains DarkSoulsRemastered.exe. Defaults to this script's folder, then its parent folder.

.PARAMETER AllowSessionAttempt
  Also sets TerminateOnSessionAttempt=0 in DSROmniRoll.ini (backed up first). Use it only if the mod
  closes the game at startup and writes DSROmniRoll_OFFLINE_GUARD_TRIGGERED.txt.

.PARAMETER Restore
  Puts the original d3d11.dll back from d3d11.dll.orig.
#>
param(
    [string]$GameDir,
    [switch]$AllowSessionAttempt,
    [switch]$Restore
)

$ErrorActionPreference = 'Stop'

$ExeSha256     = 'D18512DBA28E50A7F86C8D603EA972C85ECEF18A1455E85921110B24A95D614E'
$OrigSha256    = '978FCBDED962C9E7214E4A03E8CAF115C986E7831547962F88F149FD82020163'
$PatchedSha256 = 'A6CA05D74B0221DCBA2A3CEDEBCE781B445EE9CECD8B688A18E15418325C0BBE'

# (file offset, original bytes, patched bytes)
$PatchTable = @(
    @(0x00CFB, '90F782', '5CF881'),
    @(0x00D08, '91F782', '5DF881'),
    @(0x00D16, '92F782', '5EF881'),
    @(0x00D1E, '96F782', '62F881'),
    @(0x00D34, '96F782', '62F881'),
    @(0x0263F, '988DC8', 'C8F7CF'),
    @(0x03C9D, '4F8E', '1F01'),
    @(0x03CA6, '508E', '2001'),
    @(0x03CAF, '518E', '2101'),
    @(0x03CB8, '528E', '2201'),
    @(0x03CC1, '538E', '2301'),
    @(0x03CCA, '548E', '2401'),
    @(0x03CDE, '558E', '2501'),
    @(0x0405C, 'C48939', 'A4FC38'),
    @(0x04071, 'D18939', 'B1FC38'),
    @(0x0414D, 'C48939', 'A4FC38'),
    @(0x0416D, 'D18939', 'B1FC38'),
    @(0x04CAE, 'A191', '7104'),
    @(0x04E35, '00371A', 'A0A619'),
    @(0x04E76, '50371A', 'F0A619'),
    @(0x07663, '10D0C7', 'F039CF'),
    @(0x077F6, '007E39', 'E0F038'),
    @(0x0780E, 'E08539', 'C0F838'),
    @(0x07A96, '606839', '40DB38'),
    @(0x0EA75, '10D0C7', 'F039CF'),
    @(0x0F6E0, '507EC7', '30E8CE'),
    @(0x0F742, '70', '50'),
    @(0x0F770, '68', '48'),
    @(0x0F970, '827E39', '62F138'),
    @(0x0FFB0, '758139', '55F438'),
    @(0x105E0, '4F8E', '1F01'),
    @(0x109DA, '007E39', 'E0F038'),
    @(0x10D5B, '505538', '80C737'),
    @(0x13673, '4F8E', '1F01'),
    @(0x13E63, '68', '48'),
    @(0x14668, '68', '48'),
    @(0x16958, '40A0370020A1370070A1', 'A012370080133700D013'),
    @(0x169A0, 'D48F3900019039002A903900609039007990390099903900B590', 'A4023900D1023900FA0239003003390049033900690339008503'),
    @(0x169CB, '37ADE0FFE87AAD', 'F7A9E0FFE83AAA'),
    @(0x1735F, '3246373930', '3146383543'),
    @(0x173D2, '3246373930', '3146383543')
)

function Get-Sha256Hex([byte[]]$Bytes) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') }
    finally { $sha.Dispose() }
}

function Convert-HexToBytes([string]$Hex) {
    $out = New-Object byte[] ($Hex.Length / 2)
    for ($i = 0; $i -lt $out.Length; $i++) { $out[$i] = [Convert]::ToByte($Hex.Substring($i * 2, 2), 16) }
    return ,$out
}

function Find-GameDir {
    if ($GameDir) { return $GameDir }
    foreach ($candidate in @($PSScriptRoot, (Split-Path $PSScriptRoot -Parent))) {
        if (Test-Path (Join-Path $candidate 'DarkSoulsRemastered.exe')) { return $candidate }
    }
    return (Read-Host 'Folder that contains DarkSoulsRemastered.exe')
}

$dir = Find-GameDir
$exe = Join-Path $dir 'DarkSoulsRemastered.exe'
$dll = Join-Path $dir 'd3d11.dll'
$bak = Join-Path $dir 'd3d11.dll.orig'
$ini = Join-Path $dir 'DSROmniRoll.ini'

if (-not (Test-Path $exe)) { throw "DarkSoulsRemastered.exe not found in '$dir'." }

if ($Restore) {
    if (-not (Test-Path $bak)) { throw "No backup found at '$bak'." }
    if ((Get-FileHash $bak -Algorithm SHA256).Hash -ne $OrigSha256) { throw "'$bak' is not the original DSROmniRoll v1.01 DLL." }
    Copy-Item $bak $dll -Force
    Write-Host 'Restored the original d3d11.dll.'
    return
}

$exeHash = (Get-FileHash $exe -Algorithm SHA256).Hash
if ($exeHash -ne $ExeSha256) {
    throw "Unsupported DarkSoulsRemastered.exe (SHA-256 $exeHash). This patch only supports the 2018-05-22 build ($ExeSha256)."
}
if (-not (Test-Path $dll)) { throw "d3d11.dll not found in '$dir'. Install DSROmniRoll Standalone v1.01 first." }

$dllHash = (Get-FileHash $dll -Algorithm SHA256).Hash
if ($dllHash -eq $PatchedSha256) {
    Write-Host 'd3d11.dll is already patched. Nothing to do.'
} elseif ($dllHash -ne $OrigSha256) {
    throw "d3d11.dll is not DSROmniRoll Standalone v1.01 (SHA-256 $dllHash, expected $OrigSha256)."
} else {
    $bytes = [IO.File]::ReadAllBytes($dll)
    foreach ($row in $PatchTable) {
        $offset = [int]$row[0]
        $old = Convert-HexToBytes $row[1]
        $new = Convert-HexToBytes $row[2]
        for ($i = 0; $i -lt $old.Length; $i++) {
            if ($bytes[$offset + $i] -ne $old[$i]) { throw ('Unexpected byte at offset 0x{0:X}.' -f ($offset + $i)) }
            $bytes[$offset + $i] = $new[$i]
        }
    }
    $newHash = Get-Sha256Hex $bytes
    if ($newHash -ne $PatchedSha256) { throw "Patched result has SHA-256 $newHash, expected $PatchedSha256. Nothing was written." }
    if (-not (Test-Path $bak)) { Copy-Item $dll $bak }
    [IO.File]::WriteAllBytes($dll, $bytes)
    Write-Host "Patched d3d11.dll ($($PatchTable.Count) changes). Original saved as d3d11.dll.orig."
}

if ($AllowSessionAttempt) {
    if (-not (Test-Path $ini)) { throw "DSROmniRoll.ini not found in '$dir'." }
    if (-not (Test-Path "$ini.bak")) { Copy-Item $ini "$ini.bak" }
    $text = [IO.File]::ReadAllText($ini)
    $text = $text -replace '(?m)^TerminateOnSessionAttempt=\d+', 'TerminateOnSessionAttempt=0'
    [IO.File]::WriteAllText($ini, $text)
    Write-Host 'Set TerminateOnSessionAttempt=0 in DSROmniRoll.ini (backup: DSROmniRoll.ini.bak).'
}
